### ISSUE TITLE
Weights files are missing

### ISSUE THREAD

**Issue by lemairecarl** [kuangliu/torchcv#2]
There is hardcoded paths in the code that point to files that you did not include in the repo.

Can you provide them? Putting them on Google Drive would be great!

Thanks.

**Comment by kuangliu** [comment]
The script for generating net params is quite simple. Here is an example for generating model params for FPNSSD512.
```Python
import torch
from torchcv.models.fpnssd import FPNSSD512
# Download PyTorch ResNet50 model from:
# https://download.pytorch.org/models/resnet50-19c8e357.pth
d = torch.load('/path/to/resnet50-19c8e357.pth')
net = FPNSSD512(num_classes=21)
net.extractor.load_state_dict(d, strict=False)
torch.save(net.state_dict(), 'fpnssd512_21_fpn50.pth')
```

The idea is to load [pytorch/vision](https://github.com/pytorch/vision/tree/master/torchvision/models) trained models params into SSD/FPNSSD models.

**Comment by lemairecarl** [comment]
Great, thanks!

You should tell this in the README or in a comment somewhere.

**Comment by MInner** [comment]
Yes, this piece of info is still missing from the docs. There are some naming mismatches between vgg16 nets in torchvision and this repo, here is the code that properly copies convolutional weights:

```
import torch
from torchcv.models import SSD300

d = torch.load('/scratch2/model_weights/vgg16-397923af.pth')
d_proc = {'.'.join(k.split('.')[1:]): v for k, v in d.items() if 'classifier' not in k}
net = SSD300(num_classes=12)
net.extractor.features.layers.load_state_dict(d_proc, strict=False, verbose=True)
torch.save(net.state_dict(), '/scratch2/model_weights/ssd300_12.pth')
```

And please, note somewhere that SSD300\512 corresponds to the proper input image size (300 or 512), because I figured this out only by accident after quite a bit of tinkering.
